### ISSUE TITLE
Interia tensors are wrong for many objects

### ISSUE THREAD

**Issue by nickswalker** [aws-robotics/aws-robomaker-small-house-world#25]
Many small objects have very large interia values associated with them. They seem off by about a factor of 100. The [security camera is particularly bad](https://github.com/aws-robotics/aws-robomaker-small-house-world/blob/ros1/models/aws_robomaker_residential_SecurityCamera_01/model.sdf)
Gazebo screenshots with `View > Interias` on:
![Screenshot from 2020-07-31 19-25-46](https://user-images.githubusercontent.com/924295/89092291-fac3ed00-d375-11ea-8cf1-1ec1188db41b.png)

![Screenshot from 2020-07-31 19-25-11](https://user-images.githubusercontent.com/924295/89092290-fa2b5680-d375-11ea-8afb-a3c46dcd6149.png)
![Screenshot from 2020-07-31 19-24-50](https://user-images.githubusercontent.com/924295/89092289-f8fa2980-d375-11ea-8c06-0f39591737d4.png)

**Comment by ojasjoshi** [comment]
Thanks for raising the issue.. we are looking into it!

**Comment by wangvnn** [comment]
This [commit](https://github.com/aws-robotics/aws-robomaker-small-house-world/commit/f357be9146bd65c6fc0be3948fdc71de8c935905) marks all the objects in the scene as static objects to avoid objects getting simulated in physics engine with wrong inertia.
In this sample world, it is intended that all the objects are static.
In case some users need non-static objects, you can change object's static flag in the world file/model file but you need to make sure it has correct mass and inertia.
We will need to work on another pass to clean up sample models mass/inertia because they are in inconsistent state: some have wrong inertia, and same have no inertia.
